debug: true

spring:
  aop:
    proxy-target-class: true
    
    
security:
  user:
    password: none
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAobQfAWK5SlO1l4IMSOOf
          F24A9/ydKZQCvnebtlVx3DpSrzDaPclPf0jGM9PGW9rYRFrgWdtcOwgr+4bj3FSS
          HTETwyJLFD67cVNg6KxXBw1r0l9WlCJzPlmD/OT1Ev5rEU0cfXwNzAG/wy/FMHik
          666aL/fcUCdWvpOpHr5mN24BSTE9L17eIHOCAYzqALUkIzjZRoiI4D++hOHw7PHD
          HPy/6RUex3dwu2flDE5uWGtUxJH/yzBxiXJfHDneRZuSiwJEmN10pEvd4rH38xAe
          vzHdX/7wObpMaS6xZNHkcZjdoi6G8m+PThOe3HTpvB8GMNuwQOLb3y7miN1uGrSA
          IQIDAQAB
          -----END PUBLIC KEY-----
    
zuul:
  routes:
    patent:
      path: /patent/**
      url: http://localhost:9000/patent
    trademark:
      path: /trademark/**
      url: http://localhost:9001/trademark
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
      
logging:
  level:
    org.springframework.security: debug